/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.mydsl.ui.internal.SmdpDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmdpDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SmdpDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SmdpDslActivator.getInstance().getInjector(SmdpDslActivator.ORG_XTEXT_EXAMPLE_MYDSL_SMDPDSL);
	}
	
}
