/*
 * generated by Xtext
 */
package configuratorProject.cpdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import configuratorProject.cpdsl.ui.internal.CpdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CpdslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CpdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CpdslActivator.getInstance().getInjector(CpdslActivator.CONFIGURATORPROJECT_CPDSL_CPDSL);
	}
	
}
