/**
 * generated by Xtext
 */
package configuratorProject.cpdsl.serializer;

import configuratorProject.cpdsl.serializer.AbstractCpdslSemanticSequencer;

@SuppressWarnings("all")
public class CpdslSemanticSequencer extends AbstractCpdslSemanticSequencer {
}
