/**
 * generated by Xtext
 */
package configuratorProject.cpdsl.serializer;

import configuratorProject.cpdsl.serializer.AbstractCpdslSyntacticSequencer;

@SuppressWarnings("all")
public class CpdslSyntacticSequencer extends AbstractCpdslSyntacticSequencer {
}
