/*
* generated by Xtext
*/
package configuratorProject.cpdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CpdslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return configuratorProject.cpdsl.ui.internal.CpdslActivator.getInstance().getInjector("configuratorProject.cpdsl.Cpdsl");
	}
	
}
