/*
 * generated by Xtext
 */
package configuratorProject.cpdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CpdslUiModule extends configuratorProject.cpdsl.ui.AbstractCpdslUiModule {
	public CpdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
