/*
* generated by Xtext
*/
package configuratorProject.cpdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CpdslStandaloneSetup extends CpdslStandaloneSetupGenerated{

	public static void doSetup() {
		new CpdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

