/*
 * generated by Xtext
 */
package configuratorProject.cpdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CpdslRuntimeModule extends configuratorProject.cpdsl.AbstractCpdslRuntimeModule {

}
