/**
 * generated by Xtext
 */
package configuratorProject.cpdsl.ui.contentassist;

import configuratorProject.cpdsl.ui.contentassist.AbstractCpdslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CpdslProposalProvider extends AbstractCpdslProposalProvider {
}
