/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractSmdpDslSemanticSequencer;

@SuppressWarnings("all")
public class SmdpDslSemanticSequencer extends AbstractSmdpDslSemanticSequencer {
}
