/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractSmdpDslSyntacticSequencer;

@SuppressWarnings("all")
public class SmdpDslSyntacticSequencer extends AbstractSmdpDslSyntacticSequencer {
}
