/*
* generated by Xtext
*/
package configuratorProject.cpdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import configuratorProject.cpdsl.services.CpdslGrammarAccess;

public class CpdslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CpdslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected configuratorProject.cpdsl.parser.antlr.internal.InternalCpdslParser createParser(XtextTokenStream stream) {
		return new configuratorProject.cpdsl.parser.antlr.internal.InternalCpdslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public CpdslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CpdslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
