/*
* generated by Xtext
*/
package configuratorProject.cpdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CpdslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("configuratorProject/cpdsl/parser/antlr/internal/InternalCpdsl.tokens");
	}
}
