/*
* generated by Xtext
*/
package org.xtext.example.mydsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SmdpDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class MyModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMyModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMyModelContainsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMyModelContainsMyObjectParserRuleCall_2_1_0 = (RuleCall)cMyModelContainsAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cMyModelContainsAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cMyModelContainsMyObjectParserRuleCall_2_2_1_0 = (RuleCall)cMyModelContainsAssignment_2_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//myModel:
		//	{myModel} name=EString ("{" myModelContains+=myObject ("," myModelContains+=myObject)* "}")?;
		public ParserRule getRule() { return rule; }

		//{myModel} name=EString ("{" myModelContains+=myObject ("," myModelContains+=myObject)* "}")?
		public Group getGroup() { return cGroup; }

		//{myModel}
		public Action getMyModelAction_0() { return cMyModelAction_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//("{" myModelContains+=myObject ("," myModelContains+=myObject)* "}")?
		public Group getGroup_2() { return cGroup_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }

		//myModelContains+=myObject
		public Assignment getMyModelContainsAssignment_2_1() { return cMyModelContainsAssignment_2_1; }

		//myObject
		public RuleCall getMyModelContainsMyObjectParserRuleCall_2_1_0() { return cMyModelContainsMyObjectParserRuleCall_2_1_0; }

		//("," myModelContains+=myObject)*
		public Group getGroup_2_2() { return cGroup_2_2; }

		//","
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }

		//myModelContains+=myObject
		public Assignment getMyModelContainsAssignment_2_2_1() { return cMyModelContainsAssignment_2_2_1; }

		//myObject
		public RuleCall getMyModelContainsMyObjectParserRuleCall_2_2_1_0() { return cMyModelContainsMyObjectParserRuleCall_2_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }
	}

	public class MyValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMyBooleanParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMyRangeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMyStringEnumParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMyNumberEnumParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//myValue:
		//	myBoolean | myRange | myStringEnum | myNumberEnum;
		public ParserRule getRule() { return rule; }

		//myBoolean | myRange | myStringEnum | myNumberEnum
		public Alternatives getAlternatives() { return cAlternatives; }

		//myBoolean
		public RuleCall getMyBooleanParserRuleCall_0() { return cMyBooleanParserRuleCall_0; }

		//myRange
		public RuleCall getMyRangeParserRuleCall_1() { return cMyRangeParserRuleCall_1; }

		//myStringEnum
		public RuleCall getMyStringEnumParserRuleCall_2() { return cMyStringEnumParserRuleCall_2; }

		//myNumberEnum
		public RuleCall getMyNumberEnumParserRuleCall_3() { return cMyNumberEnumParserRuleCall_3; }
	}

	public class MyExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMyBinaryParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMyUnaryParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMyBooleanParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMyRangeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cMyStringEnumParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cMyNumberEnumParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cMyIdentifierParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//myExpression:
		//	myBinary | myUnary | myBoolean | myRange | myStringEnum | myNumberEnum | myIdentifier;
		public ParserRule getRule() { return rule; }

		//myBinary | myUnary | myBoolean | myRange | myStringEnum | myNumberEnum | myIdentifier
		public Alternatives getAlternatives() { return cAlternatives; }

		//myBinary
		public RuleCall getMyBinaryParserRuleCall_0() { return cMyBinaryParserRuleCall_0; }

		//myUnary
		public RuleCall getMyUnaryParserRuleCall_1() { return cMyUnaryParserRuleCall_1; }

		//myBoolean
		public RuleCall getMyBooleanParserRuleCall_2() { return cMyBooleanParserRuleCall_2; }

		//myRange
		public RuleCall getMyRangeParserRuleCall_3() { return cMyRangeParserRuleCall_3; }

		//myStringEnum
		public RuleCall getMyStringEnumParserRuleCall_4() { return cMyStringEnumParserRuleCall_4; }

		//myNumberEnum
		public RuleCall getMyNumberEnumParserRuleCall_5() { return cMyNumberEnumParserRuleCall_5; }

		//myIdentifier
		public RuleCall getMyIdentifierParserRuleCall_6() { return cMyIdentifierParserRuleCall_6; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class MyObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMyObjectAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cHasKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMyAttributeContainsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cMyAttributeContainsMyAttributeParserRuleCall_3_1_0 = (RuleCall)cMyAttributeContainsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cMyAttributeContainsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cMyAttributeContainsMyAttributeParserRuleCall_3_2_1_0 = (RuleCall)cMyAttributeContainsAssignment_3_2_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cConstrainedByKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMyObjectHasAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMyObjectHasMyConstraintParserRuleCall_4_1_0 = (RuleCall)cMyObjectHasAssignment_4_1.eContents().get(0);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cMyObjectHasAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final RuleCall cMyObjectHasMyConstraintParserRuleCall_4_2_1_0 = (RuleCall)cMyObjectHasAssignment_4_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//myObject:
		//	{myObject} name=EString "{" ("has" myAttributeContains+=myAttribute ("," myAttributeContains+=myAttribute)*)?
		//	("Constrained by" myObjectHas+=myConstraint ("," myObjectHas+=myConstraint)*)? "}";
		public ParserRule getRule() { return rule; }

		//{myObject} name=EString "{" ("has" myAttributeContains+=myAttribute ("," myAttributeContains+=myAttribute)*)?
		//("Constrained by" myObjectHas+=myConstraint ("," myObjectHas+=myConstraint)*)? "}"
		public Group getGroup() { return cGroup; }

		//{myObject}
		public Action getMyObjectAction_0() { return cMyObjectAction_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("has" myAttributeContains+=myAttribute ("," myAttributeContains+=myAttribute)*)?
		public Group getGroup_3() { return cGroup_3; }

		//"has"
		public Keyword getHasKeyword_3_0() { return cHasKeyword_3_0; }

		//myAttributeContains+=myAttribute
		public Assignment getMyAttributeContainsAssignment_3_1() { return cMyAttributeContainsAssignment_3_1; }

		//myAttribute
		public RuleCall getMyAttributeContainsMyAttributeParserRuleCall_3_1_0() { return cMyAttributeContainsMyAttributeParserRuleCall_3_1_0; }

		//("," myAttributeContains+=myAttribute)*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//myAttributeContains+=myAttribute
		public Assignment getMyAttributeContainsAssignment_3_2_1() { return cMyAttributeContainsAssignment_3_2_1; }

		//myAttribute
		public RuleCall getMyAttributeContainsMyAttributeParserRuleCall_3_2_1_0() { return cMyAttributeContainsMyAttributeParserRuleCall_3_2_1_0; }

		//("Constrained by" myObjectHas+=myConstraint ("," myObjectHas+=myConstraint)*)?
		public Group getGroup_4() { return cGroup_4; }

		//"Constrained by"
		public Keyword getConstrainedByKeyword_4_0() { return cConstrainedByKeyword_4_0; }

		//myObjectHas+=myConstraint
		public Assignment getMyObjectHasAssignment_4_1() { return cMyObjectHasAssignment_4_1; }

		//myConstraint
		public RuleCall getMyObjectHasMyConstraintParserRuleCall_4_1_0() { return cMyObjectHasMyConstraintParserRuleCall_4_1_0; }

		//("," myObjectHas+=myConstraint)*
		public Group getGroup_4_2() { return cGroup_4_2; }

		//","
		public Keyword getCommaKeyword_4_2_0() { return cCommaKeyword_4_2_0; }

		//myObjectHas+=myConstraint
		public Assignment getMyObjectHasAssignment_4_2_1() { return cMyObjectHasAssignment_4_2_1; }

		//myConstraint
		public RuleCall getMyObjectHasMyConstraintParserRuleCall_4_2_1_0() { return cMyObjectHasMyConstraintParserRuleCall_4_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class MyConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myConstraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMyIfConstraintAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMyIfConstraintMyConcreteExpressionParserRuleCall_1_0 = (RuleCall)cMyIfConstraintAssignment_1.eContents().get(0);
		private final Keyword cThenKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMyThenConstraintAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMyThenConstraintMyConcreteExpressionParserRuleCall_3_0 = (RuleCall)cMyThenConstraintAssignment_3.eContents().get(0);
		
		//myConstraint:
		//	"if" myIfConstraint=myConcreteExpression "then" myThenConstraint=myConcreteExpression;
		public ParserRule getRule() { return rule; }

		//"if" myIfConstraint=myConcreteExpression "then" myThenConstraint=myConcreteExpression
		public Group getGroup() { return cGroup; }

		//"if"
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }

		//myIfConstraint=myConcreteExpression
		public Assignment getMyIfConstraintAssignment_1() { return cMyIfConstraintAssignment_1; }

		//myConcreteExpression
		public RuleCall getMyIfConstraintMyConcreteExpressionParserRuleCall_1_0() { return cMyIfConstraintMyConcreteExpressionParserRuleCall_1_0; }

		//"then"
		public Keyword getThenKeyword_2() { return cThenKeyword_2; }

		//myThenConstraint=myConcreteExpression
		public Assignment getMyThenConstraintAssignment_3() { return cMyThenConstraintAssignment_3; }

		//myConcreteExpression
		public RuleCall getMyThenConstraintMyConcreteExpressionParserRuleCall_3_0() { return cMyThenConstraintMyConcreteExpressionParserRuleCall_3_0; }
	}

	public class MyAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMyAttributeContainsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMyAttributeContainsMyValueParserRuleCall_2_0 = (RuleCall)cMyAttributeContainsAssignment_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//myAttribute:
		//	name=EString "[" myAttributeContains=myValue "]";
		public ParserRule getRule() { return rule; }

		//name=EString "[" myAttributeContains=myValue "]"
		public Group getGroup() { return cGroup; }

		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }

		//myAttributeContains=myValue
		public Assignment getMyAttributeContainsAssignment_2() { return cMyAttributeContainsAssignment_2; }

		//myValue
		public RuleCall getMyAttributeContainsMyValueParserRuleCall_2_0() { return cMyAttributeContainsMyValueParserRuleCall_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}

	public class MyConcreteExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myConcreteExpression");
		private final Assignment cMyConcreteExAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cMyConcreteExMyExpressionParserRuleCall_0 = (RuleCall)cMyConcreteExAssignment.eContents().get(0);
		
		//myConcreteExpression:
		//	myConcreteEx=myExpression;
		public ParserRule getRule() { return rule; }

		//myConcreteEx=myExpression
		public Assignment getMyConcreteExAssignment() { return cMyConcreteExAssignment; }

		//myExpression
		public RuleCall getMyConcreteExMyExpressionParserRuleCall_0() { return cMyConcreteExMyExpressionParserRuleCall_0; }
	}

	public class MyBinaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myBinary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMyBinaryLeftAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMyBinaryLeftMyConcreteExpressionParserRuleCall_1_0 = (RuleCall)cMyBinaryLeftAssignment_1.eContents().get(0);
		private final Assignment cOparandAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOparandMyBinaryOparatorsEnumRuleCall_2_0 = (RuleCall)cOparandAssignment_2.eContents().get(0);
		private final Assignment cMyBinaryRightAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMyBinaryRightMyConcreteExpressionParserRuleCall_3_0 = (RuleCall)cMyBinaryRightAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//myBinary:
		//	"(" myBinaryLeft=myConcreteExpression Oparand=myBinaryOparators myBinaryRight=myConcreteExpression ")";
		public ParserRule getRule() { return rule; }

		//"(" myBinaryLeft=myConcreteExpression Oparand=myBinaryOparators myBinaryRight=myConcreteExpression ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//myBinaryLeft=myConcreteExpression
		public Assignment getMyBinaryLeftAssignment_1() { return cMyBinaryLeftAssignment_1; }

		//myConcreteExpression
		public RuleCall getMyBinaryLeftMyConcreteExpressionParserRuleCall_1_0() { return cMyBinaryLeftMyConcreteExpressionParserRuleCall_1_0; }

		//Oparand=myBinaryOparators
		public Assignment getOparandAssignment_2() { return cOparandAssignment_2; }

		//myBinaryOparators
		public RuleCall getOparandMyBinaryOparatorsEnumRuleCall_2_0() { return cOparandMyBinaryOparatorsEnumRuleCall_2_0; }

		//myBinaryRight=myConcreteExpression
		public Assignment getMyBinaryRightAssignment_3() { return cMyBinaryRightAssignment_3; }

		//myConcreteExpression
		public RuleCall getMyBinaryRightMyConcreteExpressionParserRuleCall_3_0() { return cMyBinaryRightMyConcreteExpressionParserRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class MyUnaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myUnary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOparandAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOparandMyUnaryOparatorsEnumRuleCall_0_0 = (RuleCall)cOparandAssignment_0.eContents().get(0);
		private final Assignment cMyUnaryExpressionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMyUnaryExpressionMyConcreteExpressionParserRuleCall_1_0 = (RuleCall)cMyUnaryExpressionAssignment_1.eContents().get(0);
		
		//myUnary:
		//	Oparand=myUnaryOparators myUnaryExpression=myConcreteExpression;
		public ParserRule getRule() { return rule; }

		//Oparand=myUnaryOparators myUnaryExpression=myConcreteExpression
		public Group getGroup() { return cGroup; }

		//Oparand=myUnaryOparators
		public Assignment getOparandAssignment_0() { return cOparandAssignment_0; }

		//myUnaryOparators
		public RuleCall getOparandMyUnaryOparatorsEnumRuleCall_0_0() { return cOparandMyUnaryOparatorsEnumRuleCall_0_0; }

		//myUnaryExpression=myConcreteExpression
		public Assignment getMyUnaryExpressionAssignment_1() { return cMyUnaryExpressionAssignment_1; }

		//myConcreteExpression
		public RuleCall getMyUnaryExpressionMyConcreteExpressionParserRuleCall_1_0() { return cMyUnaryExpressionMyConcreteExpressionParserRuleCall_1_0; }
	}

	public class MyBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myBoolean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTrueValueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTrueValueEStringParserRuleCall_0_0 = (RuleCall)cTrueValueAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFalseValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFalseValueEStringParserRuleCall_2_0 = (RuleCall)cFalseValueAssignment_2.eContents().get(0);
		
		//myBoolean:
		//	trueValue=EString ":" falseValue=EString;
		public ParserRule getRule() { return rule; }

		//trueValue=EString ":" falseValue=EString
		public Group getGroup() { return cGroup; }

		//trueValue=EString
		public Assignment getTrueValueAssignment_0() { return cTrueValueAssignment_0; }

		//EString
		public RuleCall getTrueValueEStringParserRuleCall_0_0() { return cTrueValueEStringParserRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//falseValue=EString
		public Assignment getFalseValueAssignment_2() { return cFalseValueAssignment_2; }

		//EString
		public RuleCall getFalseValueEStringParserRuleCall_2_0() { return cFalseValueEStringParserRuleCall_2_0; }
	}

	public class MyIdentifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myIdentifier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMyIntentifierIsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cMyIntentifierIsMyAttributeCrossReference_1_0 = (CrossReference)cMyIntentifierIsAssignment_1.eContents().get(0);
		private final RuleCall cMyIntentifierIsMyAttributeEStringParserRuleCall_1_0_1 = (RuleCall)cMyIntentifierIsMyAttributeCrossReference_1_0.eContents().get(1);
		
		//myIdentifier:
		//	"*" myIntentifierIs=[myAttribute|EString];
		public ParserRule getRule() { return rule; }

		//"*" myIntentifierIs=[myAttribute|EString]
		public Group getGroup() { return cGroup; }

		//"*"
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }

		//myIntentifierIs=[myAttribute|EString]
		public Assignment getMyIntentifierIsAssignment_1() { return cMyIntentifierIsAssignment_1; }

		//[myAttribute|EString]
		public CrossReference getMyIntentifierIsMyAttributeCrossReference_1_0() { return cMyIntentifierIsMyAttributeCrossReference_1_0; }

		//EString
		public RuleCall getMyIntentifierIsMyAttributeEStringParserRuleCall_1_0_1() { return cMyIntentifierIsMyAttributeEStringParserRuleCall_1_0_1; }
	}

	public class MyRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFromAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFromINTTerminalRuleCall_0_0 = (RuleCall)cFromAssignment_0.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cToAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cToINTTerminalRuleCall_2_0 = (RuleCall)cToAssignment_2.eContents().get(0);
		
		//myRange:
		//	from=INT "-" to=INT;
		public ParserRule getRule() { return rule; }

		//from=INT "-" to=INT
		public Group getGroup() { return cGroup; }

		//from=INT
		public Assignment getFromAssignment_0() { return cFromAssignment_0; }

		//INT
		public RuleCall getFromINTTerminalRuleCall_0_0() { return cFromINTTerminalRuleCall_0_0; }

		//"-"
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }

		//to=INT
		public Assignment getToAssignment_2() { return cToAssignment_2; }

		//INT
		public RuleCall getToINTTerminalRuleCall_2_0() { return cToINTTerminalRuleCall_2_0; }
	}

	public class MyStringEnumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myStringEnum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValuesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cValuesEStringParserRuleCall_0_0 = (RuleCall)cValuesAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cValuesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValuesEStringParserRuleCall_1_1_0 = (RuleCall)cValuesAssignment_1_1.eContents().get(0);
		
		//myStringEnum:
		//	values+=EString ("," values+=EString)*;
		public ParserRule getRule() { return rule; }

		//values+=EString ("," values+=EString)*
		public Group getGroup() { return cGroup; }

		//values+=EString
		public Assignment getValuesAssignment_0() { return cValuesAssignment_0; }

		//EString
		public RuleCall getValuesEStringParserRuleCall_0_0() { return cValuesEStringParserRuleCall_0_0; }

		//("," values+=EString)*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//values+=EString
		public Assignment getValuesAssignment_1_1() { return cValuesAssignment_1_1; }

		//EString
		public RuleCall getValuesEStringParserRuleCall_1_1_0() { return cValuesEStringParserRuleCall_1_1_0; }
	}

	public class MyNumberEnumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "myNumberEnum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValuesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cValuesEDoubleParserRuleCall_0_0 = (RuleCall)cValuesAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cValuesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValuesEDoubleParserRuleCall_1_1_0 = (RuleCall)cValuesAssignment_1_1.eContents().get(0);
		
		//myNumberEnum:
		//	values+=EDouble ("," values+=EDouble)*;
		public ParserRule getRule() { return rule; }

		//values+=EDouble ("," values+=EDouble)*
		public Group getGroup() { return cGroup; }

		//values+=EDouble
		public Assignment getValuesAssignment_0() { return cValuesAssignment_0; }

		//EDouble
		public RuleCall getValuesEDoubleParserRuleCall_0_0() { return cValuesEDoubleParserRuleCall_0_0; }

		//("," values+=EDouble)*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//values+=EDouble
		public Assignment getValuesAssignment_1_1() { return cValuesAssignment_1_1; }

		//EDouble
		public RuleCall getValuesEDoubleParserRuleCall_1_1_0() { return cValuesEDoubleParserRuleCall_1_1_0; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDouble");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Keyword cFullStopKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_0_3 = (RuleCall)cGroup_0.eContents().get(3);
		private final Group cGroup_0_4 = (Group)cGroup_0.eContents().get(4);
		private final Alternatives cAlternatives_0_4_0 = (Alternatives)cGroup_0_4.eContents().get(0);
		private final Keyword cEKeyword_0_4_0_0 = (Keyword)cAlternatives_0_4_0.eContents().get(0);
		private final Keyword cEKeyword_0_4_0_1 = (Keyword)cAlternatives_0_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0_4_1 = (Keyword)cGroup_0_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0_4_2 = (RuleCall)cGroup_0_4.eContents().get(2);
		private final RuleCall cEIntParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EDouble returns ecore::EDouble:
		//	"-"? INT? "." INT (("E" | "e") "-"? INT)? | EInt;
		public ParserRule getRule() { return rule; }

		//"-"? INT? "." INT (("E" | "e") "-"? INT)? | EInt
		public Alternatives getAlternatives() { return cAlternatives; }

		//"-"? INT? "." INT (("E" | "e") "-"? INT)?
		public Group getGroup_0() { return cGroup_0; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0_0() { return cHyphenMinusKeyword_0_0; }

		//INT?
		public RuleCall getINTTerminalRuleCall_0_1() { return cINTTerminalRuleCall_0_1; }

		//"."
		public Keyword getFullStopKeyword_0_2() { return cFullStopKeyword_0_2; }

		//INT
		public RuleCall getINTTerminalRuleCall_0_3() { return cINTTerminalRuleCall_0_3; }

		//(("E" | "e") "-"? INT)?
		public Group getGroup_0_4() { return cGroup_0_4; }

		//"E" | "e"
		public Alternatives getAlternatives_0_4_0() { return cAlternatives_0_4_0; }

		//"E"
		public Keyword getEKeyword_0_4_0_0() { return cEKeyword_0_4_0_0; }

		//"e"
		public Keyword getEKeyword_0_4_0_1() { return cEKeyword_0_4_0_1; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0_4_1() { return cHyphenMinusKeyword_0_4_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_0_4_2() { return cINTTerminalRuleCall_0_4_2; }

		//EInt
		public RuleCall getEIntParserRuleCall_1() { return cEIntParserRuleCall_1; }
	}
	
	
	public class MyBinaryOparatorsElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "myBinaryOparators");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAndEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAndAmpersandAmpersandKeyword_0_0 = (Keyword)cAndEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOrEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOrVerticalLineKeyword_1_0 = (Keyword)cOrEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cGtEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cGtLessThanSignKeyword_2_0 = (Keyword)cGtEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLtEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLtGreaterThanSignKeyword_3_0 = (Keyword)cLtEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cEqEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cEqEqualsSignKeyword_4_0 = (Keyword)cEqEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cIsEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cIsCanKeyword_5_0 = (Keyword)cIsEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cIfEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cIfIfKeyword_6_0 = (Keyword)cIfEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cThenEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cThenThenKeyword_7_0 = (Keyword)cThenEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum myBinaryOparators:
		//	and="&&" | or="|" | gt="<" | lt=">" | eq="=" | is="can" | if | then;
		public EnumRule getRule() { return rule; }

		//and="&&" | or="|" | gt="<" | lt=">" | eq="=" | is="can" | if | then
		public Alternatives getAlternatives() { return cAlternatives; }

		//and="&&"
		public EnumLiteralDeclaration getAndEnumLiteralDeclaration_0() { return cAndEnumLiteralDeclaration_0; }

		//"&&"
		public Keyword getAndAmpersandAmpersandKeyword_0_0() { return cAndAmpersandAmpersandKeyword_0_0; }

		//or="|"
		public EnumLiteralDeclaration getOrEnumLiteralDeclaration_1() { return cOrEnumLiteralDeclaration_1; }

		//"|"
		public Keyword getOrVerticalLineKeyword_1_0() { return cOrVerticalLineKeyword_1_0; }

		//gt="<"
		public EnumLiteralDeclaration getGtEnumLiteralDeclaration_2() { return cGtEnumLiteralDeclaration_2; }

		//"<"
		public Keyword getGtLessThanSignKeyword_2_0() { return cGtLessThanSignKeyword_2_0; }

		//lt=">"
		public EnumLiteralDeclaration getLtEnumLiteralDeclaration_3() { return cLtEnumLiteralDeclaration_3; }

		//">"
		public Keyword getLtGreaterThanSignKeyword_3_0() { return cLtGreaterThanSignKeyword_3_0; }

		//eq="="
		public EnumLiteralDeclaration getEqEnumLiteralDeclaration_4() { return cEqEnumLiteralDeclaration_4; }

		//"="
		public Keyword getEqEqualsSignKeyword_4_0() { return cEqEqualsSignKeyword_4_0; }

		//is="can"
		public EnumLiteralDeclaration getIsEnumLiteralDeclaration_5() { return cIsEnumLiteralDeclaration_5; }

		//"can"
		public Keyword getIsCanKeyword_5_0() { return cIsCanKeyword_5_0; }

		//if
		public EnumLiteralDeclaration getIfEnumLiteralDeclaration_6() { return cIfEnumLiteralDeclaration_6; }

		//"if"
		public Keyword getIfIfKeyword_6_0() { return cIfIfKeyword_6_0; }

		//then
		public EnumLiteralDeclaration getThenEnumLiteralDeclaration_7() { return cThenEnumLiteralDeclaration_7; }

		//"then"
		public Keyword getThenThenKeyword_7_0() { return cThenThenKeyword_7_0; }
	}

	public class MyUnaryOparatorsElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "myUnaryOparators");
		private final EnumLiteralDeclaration cNotEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cNotNotKeyword_0 = (Keyword)cNotEnumLiteralDeclaration.eContents().get(0);
		
		//enum myUnaryOparators:
		//	not;
		public EnumRule getRule() { return rule; }

		//not
		public EnumLiteralDeclaration getNotEnumLiteralDeclaration() { return cNotEnumLiteralDeclaration; }

		//"not"
		public Keyword getNotNotKeyword_0() { return cNotNotKeyword_0; }
	}
	
	private MyModelElements pMyModel;
	private MyValueElements pMyValue;
	private MyExpressionElements pMyExpression;
	private EStringElements pEString;
	private MyObjectElements pMyObject;
	private MyConstraintElements pMyConstraint;
	private MyAttributeElements pMyAttribute;
	private MyConcreteExpressionElements pMyConcreteExpression;
	private MyBinaryElements pMyBinary;
	private MyUnaryElements pMyUnary;
	private MyBooleanElements pMyBoolean;
	private MyIdentifierElements pMyIdentifier;
	private MyRangeElements pMyRange;
	private MyStringEnumElements pMyStringEnum;
	private MyNumberEnumElements pMyNumberEnum;
	private MyBinaryOparatorsElements unknownRuleMyBinaryOparators;
	private MyUnaryOparatorsElements unknownRuleMyUnaryOparators;
	private EBooleanElements pEBoolean;
	private EIntElements pEInt;
	private EDoubleElements pEDouble;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public SmdpDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.SmdpDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//myModel:
	//	{myModel} name=EString ("{" myModelContains+=myObject ("," myModelContains+=myObject)* "}")?;
	public MyModelElements getMyModelAccess() {
		return (pMyModel != null) ? pMyModel : (pMyModel = new MyModelElements());
	}
	
	public ParserRule getMyModelRule() {
		return getMyModelAccess().getRule();
	}

	//myValue:
	//	myBoolean | myRange | myStringEnum | myNumberEnum;
	public MyValueElements getMyValueAccess() {
		return (pMyValue != null) ? pMyValue : (pMyValue = new MyValueElements());
	}
	
	public ParserRule getMyValueRule() {
		return getMyValueAccess().getRule();
	}

	//myExpression:
	//	myBinary | myUnary | myBoolean | myRange | myStringEnum | myNumberEnum | myIdentifier;
	public MyExpressionElements getMyExpressionAccess() {
		return (pMyExpression != null) ? pMyExpression : (pMyExpression = new MyExpressionElements());
	}
	
	public ParserRule getMyExpressionRule() {
		return getMyExpressionAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//myObject:
	//	{myObject} name=EString "{" ("has" myAttributeContains+=myAttribute ("," myAttributeContains+=myAttribute)*)?
	//	("Constrained by" myObjectHas+=myConstraint ("," myObjectHas+=myConstraint)*)? "}";
	public MyObjectElements getMyObjectAccess() {
		return (pMyObject != null) ? pMyObject : (pMyObject = new MyObjectElements());
	}
	
	public ParserRule getMyObjectRule() {
		return getMyObjectAccess().getRule();
	}

	//myConstraint:
	//	"if" myIfConstraint=myConcreteExpression "then" myThenConstraint=myConcreteExpression;
	public MyConstraintElements getMyConstraintAccess() {
		return (pMyConstraint != null) ? pMyConstraint : (pMyConstraint = new MyConstraintElements());
	}
	
	public ParserRule getMyConstraintRule() {
		return getMyConstraintAccess().getRule();
	}

	//myAttribute:
	//	name=EString "[" myAttributeContains=myValue "]";
	public MyAttributeElements getMyAttributeAccess() {
		return (pMyAttribute != null) ? pMyAttribute : (pMyAttribute = new MyAttributeElements());
	}
	
	public ParserRule getMyAttributeRule() {
		return getMyAttributeAccess().getRule();
	}

	//myConcreteExpression:
	//	myConcreteEx=myExpression;
	public MyConcreteExpressionElements getMyConcreteExpressionAccess() {
		return (pMyConcreteExpression != null) ? pMyConcreteExpression : (pMyConcreteExpression = new MyConcreteExpressionElements());
	}
	
	public ParserRule getMyConcreteExpressionRule() {
		return getMyConcreteExpressionAccess().getRule();
	}

	//myBinary:
	//	"(" myBinaryLeft=myConcreteExpression Oparand=myBinaryOparators myBinaryRight=myConcreteExpression ")";
	public MyBinaryElements getMyBinaryAccess() {
		return (pMyBinary != null) ? pMyBinary : (pMyBinary = new MyBinaryElements());
	}
	
	public ParserRule getMyBinaryRule() {
		return getMyBinaryAccess().getRule();
	}

	//myUnary:
	//	Oparand=myUnaryOparators myUnaryExpression=myConcreteExpression;
	public MyUnaryElements getMyUnaryAccess() {
		return (pMyUnary != null) ? pMyUnary : (pMyUnary = new MyUnaryElements());
	}
	
	public ParserRule getMyUnaryRule() {
		return getMyUnaryAccess().getRule();
	}

	//myBoolean:
	//	trueValue=EString ":" falseValue=EString;
	public MyBooleanElements getMyBooleanAccess() {
		return (pMyBoolean != null) ? pMyBoolean : (pMyBoolean = new MyBooleanElements());
	}
	
	public ParserRule getMyBooleanRule() {
		return getMyBooleanAccess().getRule();
	}

	//myIdentifier:
	//	"*" myIntentifierIs=[myAttribute|EString];
	public MyIdentifierElements getMyIdentifierAccess() {
		return (pMyIdentifier != null) ? pMyIdentifier : (pMyIdentifier = new MyIdentifierElements());
	}
	
	public ParserRule getMyIdentifierRule() {
		return getMyIdentifierAccess().getRule();
	}

	//myRange:
	//	from=INT "-" to=INT;
	public MyRangeElements getMyRangeAccess() {
		return (pMyRange != null) ? pMyRange : (pMyRange = new MyRangeElements());
	}
	
	public ParserRule getMyRangeRule() {
		return getMyRangeAccess().getRule();
	}

	//myStringEnum:
	//	values+=EString ("," values+=EString)*;
	public MyStringEnumElements getMyStringEnumAccess() {
		return (pMyStringEnum != null) ? pMyStringEnum : (pMyStringEnum = new MyStringEnumElements());
	}
	
	public ParserRule getMyStringEnumRule() {
		return getMyStringEnumAccess().getRule();
	}

	//myNumberEnum:
	//	values+=EDouble ("," values+=EDouble)*;
	public MyNumberEnumElements getMyNumberEnumAccess() {
		return (pMyNumberEnum != null) ? pMyNumberEnum : (pMyNumberEnum = new MyNumberEnumElements());
	}
	
	public ParserRule getMyNumberEnumRule() {
		return getMyNumberEnumAccess().getRule();
	}

	//enum myBinaryOparators:
	//	and="&&" | or="|" | gt="<" | lt=">" | eq="=" | is="can" | if | then;
	public MyBinaryOparatorsElements getMyBinaryOparatorsAccess() {
		return (unknownRuleMyBinaryOparators != null) ? unknownRuleMyBinaryOparators : (unknownRuleMyBinaryOparators = new MyBinaryOparatorsElements());
	}
	
	public EnumRule getMyBinaryOparatorsRule() {
		return getMyBinaryOparatorsAccess().getRule();
	}

	//enum myUnaryOparators:
	//	not;
	public MyUnaryOparatorsElements getMyUnaryOparatorsAccess() {
		return (unknownRuleMyUnaryOparators != null) ? unknownRuleMyUnaryOparators : (unknownRuleMyUnaryOparators = new MyUnaryOparatorsElements());
	}
	
	public EnumRule getMyUnaryOparatorsRule() {
		return getMyUnaryOparatorsAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//EDouble returns ecore::EDouble:
	//	"-"? INT? "." INT (("E" | "e") "-"? INT)? | EInt;
	public EDoubleElements getEDoubleAccess() {
		return (pEDouble != null) ? pEDouble : (pEDouble = new EDoubleElements());
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
