/**
 * generated by Xtext
 */
package configuratorProject.cpdsl.validation;

import configuratorProject.cpdsl.validation.AbstractCpdslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CpdslValidator extends AbstractCpdslValidator {
}
